# Generated by Django 3.1.7 on 2021-03-23 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='moderation',
            field=models.BooleanField(default=True, verbose_name='Модерация'),
        ),
    ]
