# Generated by Django 3.1.7 on 2021-03-23 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20210323_1458'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='creator',
        ),
    ]
